apiVersion: 1

datasources:
  - name: influxdb
    type: influxdb
    access: server
    database: devops
    url: http://influxdb:8086
  - name: prometheus
    type: prometheus
    url: http://host.docker.internal:9090