{
 "title": "Key Metrics",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ProjectDeployName",
    "query": "select project from (select * from deploy) ;"
   },
   {
    "name": "WorkItemType",
    "query": "select distinct \"type\" from bug;"
   },
   {
    "name": "workItemIterationPath",
    "query": "select distinct \"iterationpath\" from bug;"
   }
  ]
 },
 "panels": [
  {
   "title": "Deployment Frequency (per week) - successful deployments - By ProjectDeployName",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"success\") as deploys FROM \"deploy\" WHERE (\"project\" =~ /^$ProjectDeployName$/) GROUP BY time(1w, 3d) , project",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Overview - Build failure rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit", "label": "success rate" }
   ],
   "targets": [
    {
     "expr": "count(azure_devops_build_info{result!=\"succeeded\"}) by (buildName) / count(azure_devops_build_info) by (buildName)    "
    }
   ]
  },
  {
   "title": "Deployment Failure Rate - By ProjectDeployName",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "deploy",
     "query": "SELECT 100 - (mean(\"success\") * 100) FROM \"deploy\" WHERE  (\"project\" =~ /^$ProjectDeployName$/) AND $timeFilter Group By time(1w, 3d), project",
     "select": [
      [
       { "params": [ "success" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "project", "operator": "=~", "value": "/^$ProjectBuildName$/" }
     ]
    }
   ]
  },
  {
   "title": "Overview - Build time average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(\r\n  azure_devops_build_status{type=\"jobDuration\"}\r\n    + on(buildID) group_left(buildName, result) (0 *azure_devops_build_latest_info{result=\"succeeded\"})\r\n) by (buildName) > 0  "
    }
   ]
  },
  {
   "title": "Time to Restore Service (Deploy) - Elapsed time between failure and success for a given ProjectDeployName",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select elap/3600/1000000000 from (select difference(\"success\") as diff, elapsed(\"success\") as elap FROM \"deploy\" where (\"project\" =~ /^$ProjectDeployName$/)) where diff > 0;",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lead Time for Changes (By WorkItemType / By IterationPath)",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  mean(\"duration\") FROM \"bug\" where (\"type\" =~ /^$WorkItemType$/)   and  (\"iterationpath\" =~ /^$workItemIterationPath$/)   group by iterationpath;",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lead Time for Changes by WorkItemType (All Iteration Paths)",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  mean(\"duration\") FROM \"bug\"   where (\"type\" =~ /^$WorkItemType$/)  group by iterationpath;",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}